default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: while-youre-at-it_development

test:
  <<: *default
  host: localhost
  database: while-youre-at-it_test

production:
  <<: *default
  database: while-youre-at-it_production
  username: while-youre-at-it
  password: <%= ENV['WHILE-YOURE-AT-IT_DATABASE_PASSWORD'] %>
